// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wlqpgpdvfdhganbbbwbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscXBncGR2ZmRoZ2FuYmJid2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MjQyMjUsImV4cCI6MjA4NTEwMDIyNX0.tzFwzW__E5Hx98Ti1G20L28XspFBUkbKIDq2j31BYX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);